# Touchscreen Log switch
obj-y	+= bbk_drivers_info.o
#obj-$(CONFIG_BBK_CARD_DETECT)	+= bbk_card_detect.o
obj-y	+= bbk_card_detect.o
obj-$(CONFIG_VIVO_GPIO)	+= gpio-vivo.o
obj-y	+= bbk_boards_version.o
obj-y	+= bbk_board_id.o


